name: release

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          cache: true
      - name: build x64
        run: go run _scripts/make.go build --GOARCH amd64 --GOOS darwin && mv dlv delve_darwin_amd64
      - name: build arm64
        run: go run _scripts/make.go build --GOARCH arm64 --GOOS darwin && mv dlv delve_darwin_arm64
      - name: Sign delve binaries
        env:
          AC_USERNAME: ${{ secrets.APPLE_DEVELOPER }}
          AC_PASSWORD: ${{ secrets.APPLE_DEVELOPER_PASSWORD }}
        run: gon -log-level=debug -log-json .github/workflows/sign.json
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            delve_darwin_amd64
            delve_darwin_arm64